CREATE DATABASE DEVOPS_TOOLS IF NOT EXISTS;
USE DEVOPS_TOOLS;

CREATE TABLE IF NOT EXISTS HEALTH_CHECK (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  endpoint VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS APPLICATION (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  healthCheckId BIGINT,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT APPLICATION_FK1 FOREIGN KEY (healthCheckId) REFERENCES HEALTH_CHECK (id),
);