apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.sslSecretName | default "flexudy.com" }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: 80